# Generated by Django 3.1.7 on 2021-06-02 07:59

from django.conf import settings
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=254, unique=True)),
                ('bio', models.TextField()),
                ('avatar_thumbnail', imagekit.models.fields.ProcessedImageField(default='img/default2.png', upload_to='img/')),
                ('location', models.TextField()),
                ('contact_information', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('moderators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
