# Generated by Django 3.0.4 on 2021-07-11 00:00

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(default='img/default2.png', upload_to='img/'),
        ),
    ]
