# Generated by Django 3.0.4 on 2021-07-11 00:27

from django.db import migrations, models
import django.db.models.deletion
import donations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('goal', models.FloatField(default=0.0)),
                ('reached', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=donations.models.upload_image_path)),
                ('send_content', models.CharField(default='0000', max_length=20)),
                ('send_number', models.CharField(default='0000', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.BooleanField(default=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Donation_Tag')),
            ],
        ),
    ]
