# Generated by Django 3.0.4 on 2021-07-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_tag',
            name='english_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
